server:
  port: 8001

spring:
  application:
    name: service-producer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #不在注册中心注册，其他服务无法调用该服务
    #register-with-eureka: false