eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8005

spring:
    application:
        name: service-feign-hystrix

feign:
    hystrix:
        enabled: true
